# Kibana 보안 설정
elasticsearchHosts: "https://loventure-elk-master:9200"

# 리소스 설정
resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

# 복제본 수
replicas: 1

# Kibana 설정
kibanaConfig:
  kibana.yml: |
    server.name: kibana
    server.host: "0.0.0.0"
    server.port: 5601
    elasticsearch.ssl.verificationMode: none

# 보안 설정 활성화
secret:
  enabled: true

tls:
  enabled: true

# Secret Mount (Elasticsearch 인증서)
secretMounts:
  - name: loventure-elk-master-certs
    secretName: loventure-elk-master-certs
    path: /usr/share/kibana/certs/loventure-elk-master-certs
    defaultMode: 0755

# 서비스 설정
service:
  type: ClusterIP
  ports:
    http: 5601

# 노드 선택자
nodeSelector:
  cloud.google.com/gke-nodepool: pitterpetter-nodes

# Pod 안전성 설정
podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

# 환경 변수
extraEnvs:
  - name: "NODE_OPTIONS"
    value: "--max-old-space-size=1024"
  - name: "ELASTICSEARCH_SERVICEACCOUNTTOKEN"
    valueFrom:
      secretKeyRef:
        name: "kibana-kibana-es-token"
        key: "token"
